/* Generated by configure utility */
#define AP_PLUGIN_PATH "/usr/lib/gogglesmm"
#define APPLICATION_MAJOR 0
#define APPLICATION_MINOR 13
#define APPLICATION_LEVEL 3
#define HAVE_ALSA_PLUGIN
#define HAVE_PULSE_PLUGIN
#define HAVE_OSS_PLUGIN
#define HAVE_EXPAT_PLUGIN
#define HAVE_OGG_PLUGIN
#define HAVE_VORBIS_PLUGIN
#define HAVE_OPUS_PLUGIN
#define HAVE_FLAC_PLUGIN
#define HAVE_MAD_PLUGIN
#define HAVE_AAC_PLUGIN
#define HAVE_MP4_PLUGIN
#define HAVE_ZLIB_PLUGIN
