.TH gogglesmm 1 "24 April 2023"
.SH NAME
gogglesmm \- Goggles Music Manager
.SH SYNOPSIS
.B gogglesmm
[options] [file]
.SH INTRODUCTION
Goggles Music Manager is a easy to use music manager and player for the Linux desktop. It comes with a podcast manager to download and/or play podcasts from the internet. Music tracks can be organized in various ways using play lists and custom filters. The buildin tag editor allows for easy editing tags in files, including adding album art and lyrics.
.SH OPTIONS
.I General Options
.TP
.B \-h, \-\-help
Display list of options
.TP
.B \-v, \-\-version
Display version information
.LP
.I Startup Options
.TP
.B \-\-tray
Start minimized to tray
.TP
.B \-\-disable-opengl
Disables opengl based features
.LP
.I Playback Control
.TP
.B \-\-play
Start playback
.TP
.B \-\-pause
Pause playback
.TP
.B \-\-play\-pause
Toggle pause / playback.
.TP
.B \-\-previous
Play previous track
.TP
.B \-\-next
Play next track
.TP
.B \-\-stop
Stop playback
.LP
.I Misc Options
.TP
.B \-\-toggle-shown
Show or Hide the main window
.TP
.B \-\-raise
Try to raise the main window
.TP
.B \-\-now\-playing
Show now playing notification
.TP
.B \-\-update\-podcasts
Refresh podcast feeds
.SH KEYBOARD SHORTCUTS
.TP
.B "Ctrl-N"
Reset default sorting order in current view.
.TP
.B "Ctrl-R"
Shuffle track list.
.TP
.B "Ctrl-B"
Toggles browse mode on or off.
.TP
.B "Ctrl-T"
Toggles Tag list in browse mode.
.TP
.B "Ctrl-Q"
Quit Goggles Music Manager.
.TP
.B "Ctrl-O"
Import files from given directory.
.TP
.B "Ctrl-J"
Jump to playing song in track list.
.TP
.BR "Ctrl-F" " or " "/"
Find
.TP
.B "Ctrl-S"
Show source browser
.TP
.B "Ctrl-P"
Start / Pause playback.
.TP
.B "Ctrl-\[rs]"
Stop playback.
.TP
.B "Ctrl-Shift-\[rs]"
Stop playback at the end of track.
.TP
.B "Ctrl-["
Play previous track.
.TP
.B "Ctrl-]"
Play next track.
.TP
.B "Ctrl-,"
Repeat Off
.TP
.B "Ctrl-."
Repeat Track
.TP
.B "Ctrl-/"
Repeat All
.TP
.B "Ctrl-A"
Select All in lists.
.TP
.B "Ctrl-W"
Close Window
.TP
.BR "F11" " or " "Ctrl-M"
Toggle between mini player and browser.
.TP
.B "F12"
Show Full Screen.
.TP
.B "F2"
Edit selected track, album, artist or tag.
.TP
.B "Del"
Delete selected track, album, artist or tag.
.SH MULTIMEDIA KEYS
.TP
Multimedia keys are supported using the GNOME Settings Daemon (requires dbus) or directly registered with the Xorg Display Server. The latter may not always work if multiple running applications are registering the same key. For both cases the following operations are permitted:
.TP
.BR 'play' " or " 'pause' " / " XF86AudioPlay " or " XF86AudioPause
Start / Pause playback.
.TP
.BR 'stop' " / " XF86AudioStop
Stop playback.
.TP
.BR 'next' " / " XF86AudioNext
Play previous track.
.TP
.BR 'prev' " / " XF86AudioPrev
Play next track.
.SH FILES
.TP
.I $(XDG_DATA_HOME)/gogglesmm/goggles.db
Music Database
.TP
.I $(XDG_DATA_HOME)/gogglesmm/filters.db
Filter Database
.TP
.I $(XDG_DATA_HOME)/gogglesmm/podcasts
Downloaded Podcasts
.TP
.I $(XDG_CONFIG_HOME)/gogglesmm/settings.rc
settings
.TP
.I $(XDG_CACHE_HOME)/gogglesmm/albumcovers.cache
Album cover cache
.TP
.I $(XDG_CACHE_HOME)/gogglesmm/icontheme.cache
Icon theme cache
.TP
.I $(XDG_CACHE_HOME)/gogglesmm/scrobbler.cache
Audio scrobbler cache
.SH AUTHOR
Sander Jansen <s.jansen@gmail.com>
